### ISSUE TITLE
How to disable tracking or cookies dropped by hubspot?

### ISSUE THREAD

**Issue by sb2nov** [snelsi/next-hubspot#131]
Is there a way for us to only use the form and disable cookie tracking? We want to only collect data via Google Tag Manager since that shows and obeys a consent form.

**Comment by snelsi** [comment]
I have no idea, to be honest.

You should probably look for the answer somewhere in the official docs / community forum:
https://knowledge.hubspot.com/account-and-setup/topics#privacy-and-consent
https://knowledge.hubspot.com/privacy-and-consent/customize-your-cookie-tracking-settings-and-consent-banner

https://community.hubspot.com/t5/GDPR/Disable-all-cookies-set-by-hubspot/m-p/423132
https://community.hubspot.com/t5/Reporting-Analytics/Disable-cookies-before-consent/m-p/419294
https://community.hubspot.com/t5/CMS-Development/How-to-disable-cookie-tracking-until-user-gave-consent/td-p/811540
