### ISSUE TITLE
Form not rendering with Next.js 14.0.1

### ISSUE THREAD

**Issue by matthewwilson** [snelsi/next-hubspot#132]
**Describe the bug**

Upgrading to next 14.0.1 is causing our form to no longer load.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Tested on Chrome and Safari

**Additional context**

I added some logging for `useHubspotForm`:

```
 formCreated false
 error false
 loaded false
```

So it looks like the form isn't loading. I can confirm that the hubspot script tag is present in the html. 

The `onLoad` callback for the HubspotProvider is also called

**Comment by snelsi** [comment]
What version of `next-hubspot` are you using?

**Comment by matthewwilson** [comment]
I've tried 1.1.6 and 1.2.0. 

I'm debugging the app right now and it looks like none of my breakpoints in the HubspotProvider are hit.

`useHubspotContext` then returns `false` for the `loaded` boolean. Which means that `useHubspotForm` doesn't attempt to load the form

**Comment by matthewwilson** [comment]
Ignore that last comment about the breakpoints getting hit. 

What is actually happening is the provider is loading and successfully setting loaded to true.
But then it re-renders and sets the value back to false

**Comment by snelsi** [comment]
I've seen a similar problem with [next-recaptcha-v3](https://github.com/snelsi/next-recaptcha-v3/issues/135) before.
The client fallbacks to a "default" context value, with `loaded: false` and `error:false` as if it can't find the context provider.

I believe the problem was caused by Server side using a `CommonJS` version of the library, and client side using `ESM` version.
It was fixed by making the package [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

`next-hubspot` v1.2.0 is now Pure ESM as well. So it's surprising to see this issue being reported again

**Comment by snelsi** [comment]
Can you share a code of your repo or a minimal reproducable codepen?

**Comment by matthewwilson** [comment]
>I believe the problem was caused by Server side using a CommonJS version of the library, and client side using ESM version.
It was fixed by making the package [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

This comment pointed me on the right track. When I was debugging I noticed that I had a few different versions of this:

<img width="217" alt="Screenshot 2023-11-07 at 19 50 18" src="https://github.com/snelsi/next-hubspot/assets/7092887/7956a667-cc57-49fb-8928-77f6ac4b31b9">

Turns out dependabot had updated the next dependency to 14.0.1 but had missed all the peer dependencies. Once I got those all updated to 14.0.1 my form is working!

Thanks so much for this library and the help @snelsi !

**Comment by snelsi** [comment]
@VladyslavL 
Can you try upgrading to `v1.4.0-beta.0` please?
```npm i next-hubspot@1.4.0-beta.0```

I've made some changes to hopefully fix this issue

**Comment by bzmillerboy** [comment]
I've updated to `v1.4.0-beta.0` however I get the following build error.

`Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

**Comment by bzmillerboy** [comment]
Here is how I resolved my scenario. The following code would not load the form on page navigation with Next 13 or 14 (app directory).

```JavaScript
import { HubspotProvider } from 'next-hubspot'
import { useHubspotForm } from 'next-hubspot'

function HubspotFormContent({ formId }) {
  const { loaded, error, formCreated } = useHubspotForm({
    portalId: '20095799',
    formId: formId,
    target: '#hubspotForm',
  })

  // console.log('formId', formId)
  console.log('useHubspotForm', error, loaded, formCreated)

  return (
    <div className="max-w-xl m-auto" id="hubspotForm">
      {!loaded && <div>Loading...</div>}
    </div>
  )
}

export default function HubspotForm({ formId }: { formId: string }) {
  return (
    <HubspotProvider>
      <HubspotFormContent formId={formId} />
    </HubspotProvider>
  )
}
```

However, I switched to the recommended approach in this thread: https://github.com/snelsi/next-hubspot/issues/129

providers.tsx
```JavaScript
'use client'

import { HubspotProvider } from 'next-hubspot'

const Providers = ({ children }) => (
  <HubspotProvider>{children}</HubspotProvider>
)

export default Providers
```

layout.tsx
```JavaScript
import Providers from '@/app/providers'
...
<Providers>{children}</Providers>
...
```

HubSpotForm.tsx
```JavaScript
'use client'

import { useHubspotForm } from 'next-hubspot'

const HubspotForm = ({ formId }) => {
  const { loaded, error, formCreated } = useHubspotForm({
    portalId: '20095799',
    formId: formId,
    target: '#hubspot-form-wrapper',
  })

  return <div id="hubspot-form-wrapper" />
}

export default HubspotForm
```
