### ISSUE TITLE
Configuration option for region is not included in HubspotFormProps

### ISSUE THREAD

**Issue by mcortes19** [snelsi/next-hubspot#134]
**Describe the bug**

**To Reproduce**
1. Add a component and use the Region property
2. I get a typescript error saying: `Property 'region' does not exist on type 'IntrinsicAttributes & HubspotFormProps'`

**Expected behavior**

**Comment by snelsi** [comment]
We have a ticket related to imptoving Hubspot types here:  https://github.com/snelsi/next-hubspot/issues/1

Feel free to push a PR with types declaration file update 👇
https://github.com/snelsi/next-hubspot/blob/master/src/hubspot.types.ts

**Comment by snelsi** [comment]
Published as [`v1.3.0`](https://github.com/snelsi/next-hubspot/releases/tag/1.3.0)
